# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
       #open-pull-requests-limit: 10  # Allow up to 10 open PRs at a time
    #reviewers:
     # - "your-github-username"  # Automatically request reviews from this user
    #labels:
     # - "dependencies"  # Apply this label to Dependabot PRs
    #ignore:
     # - dependency-name: "react-scripts"  # Ignore updates for create-react-app scripts
      #  versions: ["5.x"]  # Example: Ignore major version 5 updates
    #commit-message:
     # prefix: "chore(deps):"  # Custom commit message prefix
      #include: "scope"  # Include package name in commit messages
    #rebase-strategy: "auto"  # Automatically rebase when conflicts occur
